# Generated by Django 4.2.3 on 2023-07-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='create',
            new_name='created',
        ),
    ]
