# Generated by Django 4.2.3 on 2023-08-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_signup_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sideimage')),
                ('title', models.CharField(max_length=20)),
                ('discription', models.TextField()),
                ('price', models.BigIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
